version: '2'
services:
    sctm-database:
        container_name: SCTM_PostgreSQL
        image: postgres:11-alpine
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=sctm
        volumes:
            - ./docker-volumes/postgresql:/var/lib/postgresql
        networks:
            - sctm-net

    sctm-api:
        container_name: SCTM_API
        build: .
        #restart: always
        environment:
            - NODE_ENV=production
        ports:
            - '3000:3000'
        depends_on:
            - 'sctm-database'
        networks:
            - sctm-net

networks:
    sctm-net:
        external: true
